#!/bin/bash
# install homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# install oh-my-zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

brew update

brew install stow
stow .

brew install nvm
brew install pyenv
brew install pyenv-virtualenv
brew install rbenv

source ~/.zshrc

# install node, python
nvm install --lts
pyenv install 3.9
pyenv global 3.9

# install vscode
brew install --cask visual-studio-code

# install docker
brew install --cask docker
brew install docker-compose

# install chrome
brew install --cask google-chrome

brew install --cask github

brew install chafa
brew install htop
brew install neofetch
brew install tree
brew install glow
brew install wegt

PAM_FILE="/etc/pam.d/sudo"

# 추가할 라인
LINE="auth       sufficient     pam_tid.so"

# 파일에 라인이 이미 있는지 확인
if grep -Fxq "$LINE" "$PAM_FILE"; then
    echo "The line is already present in the file."
else
    # 백업 파일 생성
    sudo cp "$PAM_FILE" "$PAM_FILE.bak"
    
    # 'required'가 포함된 첫 번째 줄을 찾아 그 위에 삽입
    sudo awk -v new_line="$LINE" '/required/ && !inserted {print new_line; inserted=1} {print}' "$PAM_FILE" | sudo tee "$PAM_FILE" > /dev/null
    
    echo "The line has been added above the first 'required' line in the file."
fi